name: SSH test

on:
  workflow_dispatch: # запускается вручную из вкладки Actions

jobs:
  connect-to-server:
    runs-on: ubuntu-latest
    steps:
      - connection: Setup SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

      - name: Connect and run command
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER || 'root' }}
        run: |
          ssh -i ~/.ssh/id_ed25519 $SSH_USER@$SSH_HOST "echo '✅ Успешное подключение!'; whoami; ls -la /"

      - logic: Change directory permissions
        run: |
          ssh -i ~/.ssh/id_ed25519 $SSH_USER@$SSH_HOST "chmod -R 755 /home/brewhlale/test && echo 'Права изменены!'"

